### ISSUE TITLE
Almost Imposible game.

### ISSUE THREAD

**Issue by PabloRuizCuevas** [Dae314/placeit-game#1]
This is not a bug,I think the idea of the game is very cool, so i wanted to check the math of how to win it and what is the best strategy.

The math here is complex but I have calculated for a continuous variable with 20 buckets the chance of winning would be of 1 over 10 thousands. I wanted to ask if the creator have won this game at any moment, but unless my math is wrong, I think is humanly impossible to do it, as playing the optimal strategy is also super hard if you are not an human calculator.

The probability for a case where  the number can have decimals is precisely:  0.00012532022859694

**Comment by Dae314** [comment]
Neither my friend nor I have won a game legitimately.

However, it is possible to win, and there is a win condition check built into the app.

I dabbled with creating a solver using a hypergeometric distribution, but the results didn't reveal anything new about the problem, so I didn't take it farther. I believe this is the most accurate probability model to use because you will need to draw exactly a certain number of values within specific ranges in order to win.

Another person who tried to model the game got 0.01% win rate for all 20 tiles placed, but they didn't share their methods so I didn't validate it.

**Comment by Dae314** [comment]
I decided to make a PlaceIt simulator to help teach myself Go, and I modeled several strategies. I've validated that ~0.01% win rate is correct with "optimal" strategy.

For the strategies that I tested, the "optimal" strategy is actually pretty humanly doable. I called it binning. For a set of empty slots, calculate the range of values between its nearest placed numbers (0 if it's at the front, 1001 if it's at the rear), then divide that range evenly among the open slots to get each slot's bin range. Simply place the number you received in the slot with the corresponding bin range.

For example: You draw a 335, and there are 3 slots for you to choose from with limits of 311 and 592. The total range is 281, split across 3 slots means your bins look like:

312 - 404 (92)
405 - 497 (92)
498 - 591 (93)

Which means your 335 should go in the first "bin" which is the first open slot.

https://github.com/Dae314/placeit-sim

**Comment by PabloRuizCuevas** [comment]
Hi, actually i derived mathematically the best possible strategy on the game, not by modelling strategies but by mathematically proving it, I was consider to write a paper on it, if you are interested to collaborate with it tell me and we can do it together.

I did already started the paper etc and I can share it with you, but didn't have much time to continue with it. and properly finish it. What I can tell you is that your prior guess about the hyper-geometric  it was the correct one and the binning that you propose now is slightly sub-optimal.

Regards.

**Comment by Dae314** [comment]
I'd be willing to help out where I can! But I'm not an academic, and I've never worked on a formal published paper before, so I'm not sure how much I can actually do for you.

I suspect that there's something wrong with my implementation of the hyper-geometric distribution in my simulator, but the results came so close that I didn't see value in continuing to work on it.

**Comment by PabloRuizCuevas** [comment]
Cool, nice, I don't think you need a lot of experience on writing papers for having a valuable contribution. Just motivation. for me alone it was too much work, but I already make a bunch of progress and would be cool to have it done and published.

You could help writing, double checking the formulas, implementations, charts etc. also you gave the idea of the paper on one way or another, so I find cool if you participate.

For me the paper is about a very narrow and special "sorting algorithm", where you need to sort things as they come, so is a bunch of math.

You can start checking it here (is in python), where I solved the infinitesimal case with numbers between 0 and 1 with the binomial distribution: 

https://github.com/PabloRuizCuevas/probability-sorting/blob/main/notebooks/plots.ipynb

Sorry in advance that I didn't do the code in a way meant to be presented, I can walk you through it  if you want or update it a bit so is better.

The real case (Discrete) of the game is harder, but the implementation is _partially_ done there as well. Apart from this repo I started the paper itself, but check it out the repo first and write me a email pablo.r.c@live.com. we can check out how to split the work.

**Comment by PabloRuizCuevas** [comment]
For completeness, the last discrete result gave:

P20 = 0.00013350668877107355 from 1 to 1000 inclusive
And If 999 then: P20 = 0.0001335151668432681
